; --------------------------------------------------------------------
; This local target allows the Ansible playbook to also be run locally
; from within a debix. Simply add the tags `--tags local` when running
; --------------------------------------------------------------------
[local]
127.0.0.1 ansible_connection=local ansible_user=debix



; --------------------------------------------------------------------
; List of all debixes in the network, first IP is their currently
; reachable address, while custom_address is the IP that it will be 
; set to when running `tasks/network.yaml`
; --------------------------------------------------------------------

[asedummy]
192.168.0.217 ansible_user=debix custom_address=192.168.0.100

[ase01]
192.168.0.101 ansible_user=debix custom_address=192.168.0.101

; [ase02]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.102

; [ase03]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.103

; [ase04]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.104

; [ase05]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.105

; [ase06]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.106

; [ase07]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.107

; [ase08]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.108

; [ase09]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.109

; [ase10]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.110

; [ase11]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.111

; [ase12]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.112

; [ase13]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.113

; [ase14]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.114

; [ase15]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.115

; [ase16]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.116

; [ase17]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.117

; [ase18]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.118

; [ase19]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.119

; [ase20]
; 192.168.0.XX ansible_user=debix custom_address=192.168.0.120

[cluster:children]
asedummy
ase01
; ase02
; ase03
; ase04
; ase05
; ase06
; ase07
; ase08
; ase09
; ase10
; ase11
; ase12
; ase13
; ase14
; ase15
; ase16
; ase17
; ase18
; ase19
; ase20