; --------------------------------------------------------------------
; This local target allows the Ansible playbook to also be run locally
; from within a debix. Simply add the tags `--tags local` when running
; --------------------------------------------------------------------
[local]
127.0.0.1 ansible_connection=local ansible_user=debix



; --------------------------------------------------------------------
; List of all debixes in the network, first IP is their currently
; reachable address, while custom_address is the IP that it will be 
; set to when running `tasks/network.yaml`
;
; As an example: the following line will ensure that the debix that is
; currently at addess 1.2.3.4 will at the end of the script request
; a static IP address of 5.6.7.8. It will change the hostname to 
; 'roverexample' and always connect with the user 'debix'.
; 
; [roverexample]
; 1.2.3.4 ansible_user=debix custom_address=5.6.7.8
;
; --------------------------------------------------------------------


[roverbuilder]
192.168.0.100 ansible_user=debix custom_address=192.168.0.100 servo_trim=0

[rover01]
192.168.0.101 ansible_user=debix custom_address=192.168.0.101 servo_trim=-0.55 # and with scaler value of 0.8

[rover02]
192.168.0.102 ansible_user=debix custom_address=192.168.0.102 servo_trim=0.2 # and with scaler value of 0.8

[rover03]
192.168.0.103 ansible_user=debix custom_address=192.168.0.103 servo_trim=0.0 # and with scaler value of 0.8

[rover04]
192.168.0.104 ansible_user=debix custom_address=192.168.0.104 servo_trim=0.1 # and with scaler value of 0.8

[rover05]
192.168.0.105 ansible_user=debix custom_address=192.168.0.105 servo_trim=-0.45 # and with scaler value of 0.8

[rover06]
192.168.0.106 ansible_user=debix custom_address=192.168.0.106 servo_trim=0.1 # and with scaler value of 0.8

[rover07]
192.168.0.107 ansible_user=debix custom_address=192.168.0.107 servo_trim=0.05 # and with scaler value of 0.8

[rover08]
192.168.0.108 ansible_user=debix custom_address=192.168.0.108 servo_trim=-0.25 # and with scaler value of 0.8






[rover09]
192.168.0.109 ansible_user=debix custom_address=192.168.0.109 servo_trim=-0.2 # and with scaler value of 1.0

[rover10]
192.168.0.110 ansible_user=debix custom_address=192.168.0.110 servo_trim=-0.4 # and with scaler value of 1.0

[rover11]
192.168.0.111 ansible_user=debix custom_address=192.168.0.111 servo_trim=0.1 # and with scaler value of 0.8

[rover12]
192.168.0.112 ansible_user=debix custom_address=192.168.0.112 servo_trim=0.1 # and with scaler value of 1.15




[rover13]
192.168.0.113 ansible_user=debix custom_address=192.168.0.113 servo_trim=0






[fleet:children]
; roverbuilder

; rover01
; rover02
; rover03
; rover04
; rover05
; rover06
; rover07
; rover08

; rover09
; rover10
; rover11
rover12
; rover13



