---



- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/setup.yaml

- hosts: cluster
  become: true
  roles:
    - role: fubarhouse.golang
      vars:
        go_version: 1.22.0
        GOOS: linux
        GOARCH: arm64


- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network.yaml



# ------------------------------------------------------------------
# ./run.sh --tags local
# will run the same as above, but locally instead of on the cluster
# ------------------------------------------------------------------


- hosts: local
  when: ansible_env['HOME'] == /home/debix
  become: true
  tags:
    - local
    - never
  tasks:
    - import_tasks: tasks/setup.yaml

- hosts: local
  when: ansible_env['HOME'] == /home/debix
  become: true
  tags:
    - local
    - never
  roles:
    - role: fubarhouse.golang
      vars:
        go_version: 1.22.0
        GOOS: linux
        GOARCH: arm64

- hosts: local
  when: ansible_env['HOME'] == /home/debix
  become: true
  tags:
    - local
    - never
  tasks:
    - import_tasks: tasks/network.yaml

