
# Custom definitions
- hosts: fleet
  become: true
  tasks:
    - import_tasks: tasks/setup.yaml
    - import_tasks: tasks/dependencies.yaml
    - import_tasks: tasks/kernel.yaml


# Install Go - must be after setup to include curl
- hosts: fleet
  become: true
  roles:
    - role: fubarhouse.golang
      vars:
        go_version: 1.22.0
        GOOS: linux
        GOARCH: arm64

# Custom definitions
- hosts: fleet
  become: true
  tasks:
    - import_tasks: tasks/network.yaml


- hosts: roverbuilder
  become: true
  tasks:
    - import_tasks: tasks/github-runner.yaml


# ------------------------------------------------------------------
# ./run.sh --tags local
# will run the same as above, but locally instead of on the fleet
# ------------------------------------------------------------------

# Todo this doesn't work when specifying any tags^^


# - hosts: local
#   become: true
#   tags:
#     - local
#     - never
#   tasks:
#     - import_tasks: tasks/setup.yaml
#       when: ansible_env['HOME'] == '/home/debix'

# - hosts: local
#   become: true<
#   tags:
#     - local
#     - never
#   roles:
#     - role: fubarhouse.golang
#       when: ansible_env['HOME'] == '/home/debix'
#       vars:
#         go_version: 1.22.0
#         GOOS: linux
#         GOARCH: arm64

# - hosts: local
#   become: true
#   tags:
#     - local
#     - never
#   tasks:
#     - import_tasks: tasks/network.yaml
#       when: ansible_env['HOME'] == '/home/debix'

