---
- name: Fix dpkg state if interrupted
  command: dpkg --configure -a
  become: yes

- name: Install dependencies
  tags: dependencies
  become: true
  package:
    update_cache: yes
    name:
      - libzmq3-dev
      - zip
      - make
      - i2c-tools
      - command-not-found
      - apt-file
      - libi2c-dev
      - less
      - vim
      - picocom
      - build-essential
      - mpg123
      - tmux
      - python3-pip
      - libglib2.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - v4l-utils
      - unzip
      - wget
      - cmake
      - curl
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libdc1394-dev
      - ninja-build
      - alien
      - rsync
      - jq
      # roverlib-c dependencies
      - libprotobuf-c-dev
      - libzmq3-dev
      - libcjson-dev
      - auditd
      - gdb

- name: Download roverlib-c 3rd party deps
  tags:
    - dependencies
    - roverlib-c-deps
  become: true
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    clone: yes
    update: yes
    force: yes
  loop:
    - { repo: "https://github.com/joelguittet/c-list.git", dest: "/opt/c-list" }
    - { repo: "https://github.com/joelguittet/c-hashtable.git", dest: "/opt/c-hashtable" }

- name: Build and Install roverlib-c 3rd party deps
  tags:
    - dependencies
    - roverlib-c-deps
  become: true
  shell: "cd /opt/{{item}} && mkdir -p build && cd build && cmake .. && make install"
  loop:
    - "c-list"
    - "c-hashtable"

- name: Install Pip Dependencies
  become: true
  tags:
    - dependencies
    - pip-deps
  pip:
    executable: pip3.10
    name:
      - betterproto==1.2.5
      - grpclib==0.4.7
      - h2==4.2.0
      - hpack==4.1.0
      - hyperframe==6.1.0
      - loguru==0.7.3
      - multidict==6.1.0
      - pyzmq==26.2.1
      - stringcase==1.2.0
      - typing-extensions==4.12.2
      - roverlib==0.6.1

# Not needed for performance reasons
- name: Remove Unattended Upgrades
  tags: dependencies
  become: true
  package:
    update_cache: yes
    name: unattended-upgrades
    state: absent
  ignore_errors: true

