---

# Currently not used!

# The following installs the Github actions runner as found on Github.
# To add a self hosted runner go to Organization/Repo -> Settings -> Runner.

- name: Make sure runner directory exists
  tags: github-runner
  file:
    path: "/home/debix/actions-runner"
    owner: debix
    group: debix
    mode: '0755'
    state: directory


- name: Download latest runner package
  tags: github-runner
  shell: "curl -o /opt/actions-runner-linux-arm64-2.321.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-arm64-2.321.0.tar.gz"




- name: Extract the installer
  tags: github-runner
  unarchive:
    src: /opt/actions-runner-linux-arm64-2.321.0.tar.gz
    dest: /home/debix/actions-runner/
    remote_src: yes
    owner: debix
    group: debix


- name: Make sure GO path is in runner's env - stupid
  tags: github-runner
  lineinfile:
    path: /home/debix/actions-runner/.env
    line: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/debix/ase/bin
    create: true


- name: Install dependencies
  tags: github-runner
  become: true
  package:
    update_cache: yes
    name:
      - docker.io
      - libglib2.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - dnsmasq
      - dnsutils
      - ldnsutils


- name: Add the user debix to docker group
  tags: github-runner
  user:
    name: debix
    groups: docker
    append: yes




