---
# ------------------------------------------
# Copying custom built kernel files to debix
# ------------------------------------------

- name: Copy over and install kernel modules
  tags: kernel
  unarchive:
    src: "./kernel/built_blobs/6.1.22-ase2024.tar.gz"
    dest: /lib/modules

# Possibly run a depmod -a
# or after module errors or a reboot

- name: Copy over dtb files
  tags: kernel
  copy:
    src: "{{ item }}"
    dest: /home/debix/ase/linux/dtbs/
    owner: debix
    group: debix
    mode: "644"
  loop:
    - "./kernel/built_blobs/imx8mp-evk.dtb"
    - "./kernel/built_blobs/imx8mp-debix-ase2024-debixboard.dtb"

- name: Copy kernel Image to debix
  tags: kernel
  copy:
    src: "./kernel/built_blobs/Image"
    dest: /home/debix/ase/linux/kernel/
    owner: debix
    group: debix
    mode: "644"

- name: Install image to debix
  tags: kernel
  become: true
  shell: "cp --no-preserve=mode,ownership /home/debix/ase/linux/kernel/* /boot"

- name: Install dtb files
  tags: kernel
  become: true
  shell: "{{ item }}"
  loop:
    - "rm /boot/*.dtb"
    - "cp --no-preserve=mode,ownership /home/debix/ase/linux/dtbs/*.dtb /boot"
    - "mv /boot/imx8mp-evk.dtb /boot/imx8mp-evk.dtb.orig"
    - "cp --no-preserve=mode,ownership /home/debix/ase/linux/dtbs/imx8mp-debix-ase2024-debixboard.dtb /boot/imx8mp-evk.dtb"
